Feature engineering module
uc-python/advanced-python-datasci pull request #26
Opened 2021-11-26 19:04 UTC by bradleyboehmke

This PR incorporates the Feature Engineering module that will be taught during day 2 of the workshop.

2021-11-27 03:03 UTC, eswan18 commented
One small thing on something I think you merged earlier: you use the syntax `_ = adult_census.hist(figsize=(20, 14))`, but in the intro we teach students to use a semicolon for the same purpose (avoiding the ugly `<matplotlib.axes object ...>`): `adult_census.hist(figsize=(20, 14));`. For consistency, it would be nice to keep with that syntax here.

2021-11-27 04:09 UTC, eswan18 requested changes
Just a couple tiny typos

2021-11-27 04:09 UTC, eswan18 commented on notebooks/05-feat_eng.ipynb
> +    "    <p class=\"last\">We can use the <tt class=\"docutils literal\">handle_unknown</tt> parameter to ignore categories rare categories that may show up in test data but were not present in the t
typo: "categories rare categories"

2021-11-27 04:09 UTC, eswan18 commented on notebooks/05-feat_eng.ipynb
> +    "* It **transforms each subsets**. A specific transformer is applied to\n",
typo: "each subsets"

2021-11-27 04:09 UTC, eswan18 commented on notebooks/05-feat_eng.ipynb
> +    "longer in order to converge. Since our categorical features are not scaled its often recommended to increase the number of allowed iterations for linear models.</p>\n",
typo: "its" should be "it's"

2021-11-27 11:50 UTC, bradleyboehmke commented on notebooks/05-feat_eng.ipynb
> +    "    <p class=\"last\">We can use the <tt class=\"docutils literal\">handle_unknown</tt> parameter to ignore categories rare categories that may show up in test data but were not present in the t
Good catch - addressed in #27

2021-11-27 11:50 UTC, bradleyboehmke commented on notebooks/05-feat_eng.ipynb
> +    "* It **transforms each subsets**. A specific transformer is applied to\n",
Good catch - addressed in #27

2021-11-27 11:50 UTC, bradleyboehmke commented on notebooks/05-feat_eng.ipynb
> +    "longer in order to converge. Since our categorical features are not scaled its often recommended to increase the number of allowed iterations for linear models.</p>\n",
Good catch - addressed in #27

2021-11-30 03:48 UTC, eswan18 approved these changes

2021-11-30 14:38 UTC, merged